name: ferry_cache_unexpected_behaviour
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  gql_client:
    path: ../gql_client
  cupertino_icons: ^1.0.1
  ferry: ^0.9.2
  ferry_flutter: ^0.3.2
  flutter_dotenv: ^2.1.0
  get_it: ^5.0.3
  gql_http_link: ^0.3.2
  intl: ^0.17.0
  shared_preferences: ^2.0.3
  uuid: 2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  ferry_generator: ^0.3.3
flutter:
  uses-material-design: true
  assets:
    - .env
    